### ISSUE TITLE
Batches with only 1 request

### ISSUE THREAD

**Issue by bpickrel** [Xilinx/inference-server#80] opened 2022-09-27 00:36 UTC
**Describe the bug**
I wrote a Python client script to submit multiple requests in a single batch to the migraphx worker, using the method `inferAsyncOrdered()` but the worker received multiple batches each containing 1 request, even when the request timeout was set to a very loose limit of 10 seconds or more.  Investigation showed the method  Batch::addRequest() was always called from the same thread, apparently making it impossible for concurrent requests to be added to the same batch before the batcher cycled on to the next batch.

I need working multi-request batches in order to develop/test the migraphx worker feature that processes them.

**To Reproduce**
1. Run a Proteus Docker container built from forked branch https://github.com/bpickrel/inference-server/tree/Yolo_bert_models_without_history
2. Run the following commands from Proteus prompt:

```bash
proteus build --debug
pip3 install Pillow
pip3 install scipy
pip3 install onnxruntime
# tokenizers v0.13.0 won't build
pip3 install tokenizers==0.12.1
```

3.  Get the data and utility scripts for the Bert-squad10 model from the Migraphx repository.
4. Start the Inference Server in gdb.
5. Run the attached script

[migraphx_bert.py.txt](https://github.com/Xilinx/inference-server/files/9650520/migraphx_bert.py.txt)

**Expected behavior**

**Screenshots**

**OS/Versions:**
Provide any relevant tools/system information (version, compiler, OS etc.)

**Additional context**

**Comment by varunsh-xilinx** [comment] 2022-09-27 14:03
I didn't try your specific instructions but I was unable to reproduce this using a simpler test. Could you test it instead and see what you get? In the dev container:

```bash
git checkout main
# add an arbitrarily long batcher timeout to guarantee batching
sed -i '79i \    parameters.put("timeout", 10000)' ./examples/python/pt_zendnn.py
# run the example
python3 ./examples/python/pt_zendnn.py
```

This example is also using `inferAsyncOrdered()` and my [server.log](https://github.com/Xilinx/inference-server/files/9656562/server.log) for this example shows that it's batching to 32.

**Comment by varunsh-xilinx** [comment] 2022-12-13 21:38
I believe this issue has been resolved. Closing for now but please raise a new issue if you see it again

**Closed by varunsh-xilinx** 2022-12-13 21:38 UTC
Labels: bug
